version: '3.3'
services:
  application:
    image: mockin
    container_name: mockin
    env_file: .env
    environment:
      - DATABASE_URL=postgres://postgres:development@postgresql/mockin_dev
    ports:
      - 4000:4000
    depends_on:
      - postgresql
  postgresql:
    image: postgres:10
    container_name: mockin-postgres
    environment:
      - POSTGRES_DB=mockin_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    volumes:
      - mockin_psql:/var/lib/postgresql/data
volumes:
  mockin_psql: