apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mockin-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 4000
    targetPort: 4000
    nodePort: 30001
  selector: 
    name: mockin-backend
status:
  loadBalancer: {}